version: 2.1

jobs:
  test-lint-build:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
  
  build-scan-upload-docker:
    docker:
      - image: circleci/golang:1.15

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Install docker-scan-plugin
          command: |
            mkdir -p ~/.docker/cli-plugins && \
            curl https://github.com/docker/scan-cli-plugin/releases/latest/download/docker-scan_linux_amd64 -L -s -S -o ~/.docker/cli-plugins/docker-scan &&\
            chmod +x ~/.docker/cli-plugins/docker-scan

      - run:
          name: Build docker container
          command: |
            docker build --tag=$DOCKER_NAME .
            docker image ls

      - run:
          name: Upload Docker to Dockerhub
          command: |
            echo "Docker ID and Image: $DOCKER_NAME"
              docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            docker tag $DOCKER_NAME $DOCKER_USERNAME/$DOCKER_NAME:$CIRCLE_WORKFLOW_ID
            docker push $DOCKER_USERNAME/$DOCKER_NAME:$CIRCLE_WORKFLOW_ID
  

workflows:
  default:
    jobs:
      - test-lint-build
      - build-scan-upload-docker:
          requires:
            - test-lint-build
      