- name: Copy deployment configuration
  copy:
    src: "capstone-project-deployment.yaml"
    dest: $HOME

- name: Apply deployment configuration
  shell: "./bin/kubectl apply -f capstone-project-deployment.yaml"
  args:
    chdir: $HOME
