- name: Copy service configuration
  copy:
    src: "capstone-project-service.yaml"
    dest: $HOME

- name: Create service configuration
  command: "./bin/kubectl apply -f capstone-project-service.yaml"
  args:
    chdir: $HOME
